### ISSUE TITLE
Mailing list

### ISSUE THREAD

**Issue by samuelli** [samuelli/compclub#10]
Create an interested mailing list.

Public
1. Click something to sign up
2. Gets taken to a page with 1 field in a form "email" sign up for updates.
3. thank you

Backend
1. Take that email and store it in a separate object in datastore.

Admin panel
1. Have a send email button.
2. Taken to a form. There is a list of all emails default selected.
3. The form has 1 large text field. Allows admin to write an email.
4. Allows tags. eg. <firstname> to insert the first name into the email.
5. Submit
6. The backend sends individual emails to all those emails selected and replaces any tags. eg. matches and change to "Hi <firstname>," --> "Hi Sam,".

Sample code for sending an email already exists in the signup process.

**Comment by wengsern** [comment]
This part is technically done?

In emailing.html, there will be tables to choose (who to email). There is also a form to fill in Email title, Send From, and email body. 

The back end will replace << "NAME" >> and email individual emails. (need testing) [need to uncomment "message.send"]

To do: 
redirect to a preview page before sending email? 

Extra feature to make this more user friendly is to add a html editor for admin to format the email.
