### ISSUE TITLE
Mailing list unsubscribe

### ISSUE THREAD

**Issue by pdcamilleri** [samuelli/compclub#12]
Allow users to unsubscribe from the mailing list

**Comment by wengsern** [comment]
What I did:
Include an unsubscribe link in the email send to subscribers. (from emailing.html, when admin send an email to people, they will get a link for unsubscribe)
When they click on the link, it will redirect to unsubscribe.html (asking for confirmation). If confirmed, it will remove and redirect to unsubscribed.html

To do:
can someone check the unsubscribe.html and unsubscribed.html? i dont know what to write.. so i wrote random stuff

other than that.. the feature should work.. 
but people will only get the unsubscribe link if you guys send email using emailing.html (there is no form to enter email to unsubscribe)
